# Change these first
owner: Yukiko-Dev-Team
repo: Uptime

sites:
  - name: Yukiko.app
    url: https://yukiko.app
    expectedStatusCodes:
      - 200
      - 503
      - 403
  - name: Beta Yukiko.app
    url: https://beta.yukiko.app
    expectedStatusCodes:
      - 200
      - 503
      - 403
  - name: Gateway
    url: https://Gateway.yukiko.app
    expectedStatusCodes:
      - 200
      - 503
      - 403
  - name: Network JP
    url: $SECRET_IP_JP
  - name: Network USA
    url: $SECRET_IP_USA
  - name: Network EU
    url: $SECRET_IP_EU
  - name: bot
    url: $SECRET_IP_INA

status-website:
  cname: status.stellar-corp.net
  logoUrl: https://cdn.nishikino.xyz/global/SC_Logo/SC_Logo_Horizontal_Dark.svg
  name: Stellar Corporation
  introTitle: "Stellar Corporation, Also known as the Yukiko Dev Team, is a developement Agcency."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Yukiko.app
      href: https://yukiko.app

assignees:
  - Asthriona

workflowSchedule:
  graphs: "5 0 * * *"
  responseTime: "5 23 * * *"
  staticSite: "5 1 * * *"
  summary: "5 0 * * *"
  updateTemplate: "5 0 * * *"
  updates: "5 3 * * *"
  uptime: "5,20,35,50 * * * *"
